@echo off
title Opening Godot 4 Editor...
echo Opening Godot Editor for Dead Frontier...
"C:\Users\ST115\AppData\Local\Microsoft\WinGet\Packages\GodotEngine.GodotEngine_Microsoft.Winget.Source_8wekyb3d8bbwe\Godot_v4.7.1-stable_win64.exe" -e --path "%~dp0"
