@echo off
title Running Dead Frontier: Mecha & Monsters...
cd /d "%~dp0"
echo Launching Dead Frontier in %CD%...
start "" "C:\Users\ST115\AppData\Local\Microsoft\WinGet\Packages\GodotEngine.GodotEngine_Microsoft.Winget.Source_8wekyb3d8bbwe\Godot_v4.7.1-stable_win64.exe" res://scenes/main/Main.tscn
