@echo off
title Running Dead Frontier: Mecha & Monsters...
echo Launching Dead Frontier...
"C:\Users\ST115\AppData\Local\Microsoft\WinGet\Packages\GodotEngine.GodotEngine_Microsoft.Winget.Source_8wekyb3d8bbwe\Godot_v4.7.1-stable_win64.exe" --path "%~dp0" res://scenes/main/Main.tscn
